services:
  app:
    image: paralelnodev/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    working_dir: /app
    environment:
      - CI=true
    command: make test
