services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: docker.io/library/caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
