services:
  app:
    # dev-состав: пересобираем образ из Dockerfile.production
    # (базовый образ + зависимости), но запускаем в dev-режиме.
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: docker.io/library/caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
